### ISSUE TITLE
Clang "include" error

### ISSUE THREAD

**Issue by Phant76** [pl-ca/ClangAutoComplete#13]
Hi!
I find strange error - autocomplete not working for struct after "#include <*>". After search I find this http://clang.llvm.org/docs/FAQ.html

It's can be fixed, if you include libs with -I option. For example, I fix it with clang_includes=" -I/usr/include -I ." on line 107. I hope that you will be fix it too.

**Comment by pl-ca** [comment]
Hi,

I'm a little bit confused by your issue. When you attemp to `#include` any file, the clang auto-completion stops working?

Currently, the `include_dirs` settings (in the file `Sublime Text 3\Packages\ClangAutoComplete\ClangAutoComplete.sublime-settings`) should be able to add those folder to the clang includes automatically (`-I/usr/include`, etc.).

Did you fix by using hardcoded the includes rather than using the settings?
Or you changed the order of the `-I .` to be at the end?
Or did you simply not know about the settings?

Thanks!

**Comment by Phant76** [comment]
Sorry, my mistake. I was surprised that Clang not include standart libs in $PATH. It's strange.
