### ISSUE TITLE
request: project-specific settings

### ISSUE THREAD

**Issue by canfoderiskii** [pl-ca/ClangAutoComplete#26]
Is there any possiblilty that adding a 'read project-specific setting' feature before processing a file?

Maybe the project-specific setting file is a .clang_complete file as used by vim's clang_complete plugin.

ClangAutoComplete can search up from the directory tree for the setting file. If it's found, use it to add parameters passed to clang.

**Comment by pl-ca** [comment]
Sounds like a useful feature and I will try to implement it. However, I'm a little bit busy these days so it may take a while.

Otherwise I can suggest you to go submit this request to [this fork of my plugin](https://github.com/niosus/EasyClangComplete). @niosus is a bit more active than me at the moment and may respond quicker to this request.

**Comment by canfoderiskii** [comment]
Thank you very much for the reply and thank you for the great plugin.

I'll take your advice and submit a request to that fork version too. 

In the meantime, i'll wait for new version of ClangAutoComplete. I can try both.

**Comment by pl-ca** [comment]
Hello, I implemented this feature based on your suggestion.
Whenever package control updates you to the latest version, you can create a file named ".clangautocomplete" in the base folder of you project, and it should contain the same format as the current user settings. It will be loaded instead of the general user settings.
Let me know if you have any trouble with this!

**Comment by canfoderiskii** [comment]
@pl-ca ok, thank you for the upgrade, i'll try it sometime.
